### PR TITLE
able to get channel overrides* (properly)

### PR DESCRIPTION
**Pull request by VMpc**
I was attempting to add mute guild (/channel) /group chat support for gord but then ran into this issue with the discordgo fork

Edit: to clarify, there is no possible way to get channel overrides currently (due to this issue)

### CODE REVIEW

**Comment by yellowsink** [comment]
What is the purpose of making the channel id an `interface{}`? so it's effectively dynamically typed?

**Comment by VMpc** [comment]
Discord causes it to either be a float64 or a string (I believe it's random) but yeah I believe they did it to stop custom discord clients (or just some dev at discord had an aneurysm) but to convert it from the interface{} you could just use code like this 
(it was put in a issue (on regular discordgo) by the original cordless maintainer but never accepted due to it being user account only [624](https://github.com/bwmarrin/discordgo/issues/624)

Edit: I modified my local packages to have this fix and nothing needs to be changed except this pull request (and the one I'll do on gord when I'm finished), everything works fine (P.s it's almost done)
https://streamable.com/p0jqhr

```go
func convertChannelID(channelID interface{}) string {
	switch reflect.TypeOf(channelID).String() {
	case "float64":
		return fmt.Sprint(channelID.(float64))
	case "string":
		return channelID.(string)
	}

	return ""
}
```

**Comment by yellowsink** [comment]
> Discord causes it to either be a float64 or a string

That's... very stupid. Welp okay I guess, makes sense.

**Comment by yellowsink** [comment]
nice music in that vid btw

**Comment by VMpc** [comment]
> > Discord causes it to either be a float64 or a string
> 
> That's... very stupid. Welp okay I guess, makes sense.

Extremely and ik the amazing 10 seconds of it that sounds like I'm listening to a clock thank you lmao here's the full thing 
https://open.spotify.com/track/5zHPOglU6vWzaaJJRN7c7z?si=79451d4cda2b499a

**Pull request merged**
